### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by alamb91** [Nanyx/gen-spe-mkr#3]
I can't get it to work no matter what I do. Can you provide better instructions?

**Comment by Nanyx** [comment]
I'll set it up online soon.

**Comment by Nanyx** [comment]
look at this website ;)
[https://gsm-tool.000webhostapp.com/](https://gsm-tool.000webhostapp.com/)

**Comment by Nanyx** [comment]
You can also grab the latest release and use a local server to serve it.
